import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { AnimatePresence } from "motion/react";

const prompt = Prompt({
  weight: ["600", "500", "400", "300"],
  subsets: ["thai", "latin"],
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "YWC-HW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prompt.variable} antialiased`}
      >
        <AnimatePresence>
          {children}
        </AnimatePresence>
      </body>
    </html>
  );
}
